name: test
on: push
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Lint
        run: echo "analyzing code..."
  test:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Test
        run: echo "testing code..."
  deploy:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run deploy
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
